[project]
name = "guide_generator_pro"
version = "0.1.0"
description = "guide_generator_pro using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.8.1"
]

[project.scripts]
guide_generator_pro = "guide_generator_pro.main:run"
run_crew = "guide_generator_pro.main:run"
train = "guide_generator_pro.main:train"
replay = "guide_generator_pro.main:replay"
test = "guide_generator_pro.main:test"
run_with_trigger = "guide_generator_pro.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
